#profile ??
#???? ? ??? ??? ?? ??? ???? ??? prod? test? ??
#active ? test? ???? test? ?? ?? ???? ???? ?? ???? ??
spring:
  profiles:
    default: test
    #active: prod #0206주석처리
  # ?? jpa ??
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect


